import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.browse': 'Browse',
    'nav.following': 'Following',
    'nav.explore': 'Explore Creators',
    'nav.become_creator': 'Become a Creator',
    'nav.how_it_works': 'How It Works',
    'nav.leaderboard': 'Leaderboard',
    'nav.staking': 'Staking',
    'nav.login': 'Login',
    'nav.beta_stage': 'Beta Stage',
    
    // Categories
    'category.memecoins': 'Memecoins',
    'category.gaming': 'Gaming',
    'category.development': 'Development',
    'category.trading': 'Trading',
    'category.education': 'Education',
    'category.nsfw': 'MISC',
    'category.categories': 'Categories',
    'category.socials': 'Socials',
    
    // User Menu
    'user.settings': 'Settings',
    'user.subscription_settings': 'Subscription Settings',
    'user.obs_streaming': 'OBS Streaming',
    'user.balance': 'Balance',
    'user.wallet': 'Wallet',
    'user.email': 'Email',
    'user.sign_out': 'Sign Out',
    'user.disconnect': 'Disconnect',
    'user.connected_wallet': 'Connected Wallet',
    'user.google_user': 'Google User',
    
    // Socials
    'social.x_twitter': 'X (Twitter)',
    'social.telegram': 'Telegram',
    'social.email': 'Email',

    // Footer
    'footer.description': 'The ultimate streaming platform for WenLive.fun users and creators. Stream, donate, and engage with the WenLive.fun community.',
    'footer.platform': 'Platform',
    'footer.legal': 'Legal',
    'footer.connect': 'Connect',
    'footer.home': 'Home',
    'footer.browse_streams': 'Browse Streams',
    'footer.creators': 'Creators',
    'footer.terms_of_service': 'Terms of Service',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.twitter': 'Twitter',
    'footer.status': 'Status',
    'footer.copyright': 'All rights reserved.',

    // Following Page
    'following.login_description': 'Login to follow creators and see their live streams and VODs.',
    'following.go_home': 'Go Home',
    'following.description': 'Live streams and VODs from creators you follow',
    'following.no_content_title': 'No Content Yet',
    'following.no_content_description': 'Follow some creators to see their live streams and VODs here. Discover new creators to follow!',
    'following.live_tab': 'Live',
    'following.vods_tab': 'VODs',
    'following.no_live_streams': 'No live streams from followed creators at the moment.',
    'following.no_vods': 'No VODs from followed creators yet.',

    // Homepage
    'home.hero.title': 'Stream, Connect & Earn with WenLive.fun',
    'home.hero.subtitle': 'The decentralized streaming platform on Solana',
    'home.hero.description': 'Create live streams, watch your favorite creators, and earn rewards in a truly decentralized environment.',
    'home.hero.start_watching': 'Start Watching',
    'home.hero.become_creator': 'Become a Creator',
    'home.hero.tagline': 'Stream. Earn. Repeat. On-chain and unstoppable — welcome to WenLive.fun.',
    'home.contract_address': 'Contract Address',
    'home.copy_address': 'Copy Address',
    'home.address_copied': 'Address copied to clipboard!',
    'home.contract_copied': 'Contract Address copied to clipboard!',
    'home.live_channels': 'Live Channels',
    'home.featured_creators': '🔥 Featured Creators',
    'home.creator_uploads': 'Creator Uploads',
    'home.recently_streamed': 'Recently Streamed',
    'home.no_live_streams': 'No live streams at the moment',
    'home.no_uploads': 'No creator uploads available',
    'home.no_recent_vods': 'No recent VODs available',
    'home.no_live_or_creators': 'No live streams or featured creators at the moment',
    'home.no_uploaded_videos': 'No uploaded videos yet',
    'home.no_past_streams': 'No past streams yet',
    'home.view_all_streams': 'View All Streams',
    'home.view_all_uploads': 'View All Uploads',
    'home.view_all_vods': 'View All VODs',
    'home.view_all_live': 'View All Live →',
    'home.view_all_uploads_link': 'View All Uploads →',
    'home.view_all_vods_link': 'View All VODs →',
    'home.loading_streams': 'Loading live streams...',
    'home.loading_uploads': 'Loading creator uploads...',
    'home.loading_vods': 'Loading recent VODs...',
    'home.loading_content': 'Loading content...',
    'home.refresh': 'Refresh',
    'home.be_first_live': 'Be the first to go live!',
    'home.start_uploading': 'Start uploading content!',
    'home.start_creating': 'Start creating content!',
    'home.failed_live_streams': 'Failed to load live streams. Please try refreshing.',
    'home.failed_uploads': 'Failed to load uploaded videos. Please try refreshing.',
    'home.failed_recent_videos': 'Failed to load recent videos. Please try refreshing.',

    // StartWatching Page
    'watch.discover_category': 'Discover Content By Category',
    'watch.explore_category': 'Explore',
    'watch.content': 'Content',
    'watch.find_content': 'Find live streams and VODs in the',
    'watch.category_text': 'category.',
    'watch.browse_categories': 'Browse through various categories to find live streams, VODs, and other content that interest you.',
    'watch.search_placeholder': 'Search streams or creators (coming soon)',
    'watch.search': 'Search',
    'watch.live_streams': 'Live Streams',
    'watch.vods': 'VODs',
    'watch.total': 'total',
    'watch.no_content_category': 'No content found in',
    'watch.at_moment': 'at the moment.',
    'watch.view_all_categories': 'View All Categories',
    'watch.no_content_available': 'No content available in',
    'watch.load_more': 'Load More',
    'watch.remaining': 'remaining',
    'watch.no_categories': 'No categories available to display.',

    // Content States
    'content.loading': 'Loading...',
    'content.error': 'Error loading content',
    'content.no_content': 'No content available',
    'content.try_again': 'Try Again',
    'content.load_more': 'Load More',
    'content.refresh': 'Refresh',
    'content.search_placeholder': 'Search creators, live streams, VODs...',

    // Stream States
    'stream.live': 'LIVE',
    'stream.upload': 'UPLOAD',
    'stream.processing': 'PROCESSING',
    'stream.vod': 'VOD',
    'stream.offline': 'OFFLINE',
    'stream.starting': 'STARTING',
    'stream.viewers': 'viewers',
    'stream.viewer': 'viewer',
    'stream.watching': 'Watching',
    'stream.processing_text': 'Processing...',

    // Time
    'time.just_now': 'Just now',
    'time.minute_ago': 'minute ago',
    'time.minutes_ago': 'minutes ago',
    'time.hour_ago': 'hour ago',
    'time.hours_ago': 'hours ago',
    'time.day_ago': 'day ago',
    'time.days_ago': 'days ago',
    'time.week_ago': 'week ago',
    'time.weeks_ago': 'weeks ago',
    'time.month_ago': 'month ago',
    'time.months_ago': 'months ago',
    'time.year_ago': 'year ago',
    'time.years_ago': 'years ago',

    // Browse Page
    'browse.title': 'Browse Content',
    'browse.subtitle': 'Discover live streams and videos from creators',
    'browse.live_streams': 'Live Streams',
    'browse.recent_vods': 'Recent VODs',
    'browse.no_streams': 'No live streams available',
    'browse.no_vods': 'No VODs available',
    'browse.filter_by_category': 'Filter by Category',
    'browse.all_categories': 'All Categories',

    // VODs Page
    'vods.title': 'All VODs',
    'vods.subtitle': 'Explore all recorded streams and content from our creators',
    'vods.total_count': 'total',
    'vods.no_vods': 'No VODs Available',
    'vods.no_vods_description': 'There are no recorded streams available at the moment.',
    'vods.loading': 'Loading VODs...',
    'vods.error': 'Error Loading VODs',
    'vods.error_description': 'Unable to load video content. Please try again later.',
    'vods.remaining': 'remaining',

    // Explore Creators
    'explore.title': 'Explore Creators',
    'explore.subtitle': 'Discover talented creators on our platform.',
    'explore.no_creators': 'No creators found yet.',
    'explore.no_creators_description': 'Check back later or be the first to create a profile!',
    'explore.error_loading': 'Error Loading Creators',
    'explore.error_description': 'There was an error fetching the creator profiles.',

    // Leaderboard
    'leaderboard.title': 'Leaderboards',
    'leaderboard.subtitle': 'Top performers and referrers',
    'leaderboard.creators': 'Creators',
    'leaderboard.referrals': 'Referrals',
    'leaderboard.creator_title': 'Creator Leaderboard',
    'leaderboard.creator_subtitle': 'Top creators since June 28, 2025',
    'leaderboard.no_data': 'No creator data available yet.',
    'leaderboard.streams': 'Streams',
    'leaderboard.total_hours': 'Total Hours',
    'leaderboard.champion': 'Champion',
    'leaderboard.runner_up': 'Runner-up',
    'leaderboard.third_place': 'Third Place',
    'leaderboard.referral_title': 'Referral Leaderboard',
    'leaderboard.rank': 'Rank',
    'leaderboard.user': 'User',
    'leaderboard.total': 'Total',
    'leaderboard.valid': 'Valid',
    'leaderboard.last_activity': 'Last Activity',
    'leaderboard.no_referrals': 'No referrals yet!',
    'leaderboard.no_referrals_description': 'Be the first to refer friends and claim the top spot.',
    'leaderboard.referral_system': 'Referral System',
    'leaderboard.total_referrals_desc': 'Users who sign up with your link',
    'leaderboard.valid_referrals_desc': 'Users who stream or watch for 60+ seconds',
    'leaderboard.ranking_desc': 'Sorted by valid referrals first, then total referrals',
    'leaderboard.loading': 'Loading leaderboard...',

    // Referral System
    'referral.title': 'Your Referral Link',
    'referral.url_label': 'Referral URL',
    'referral.copy_url': 'Copy URL',
    'referral.url_copied': 'Referral URL copied to clipboard!',
    'referral.how_it_works': 'How it works:',
    'referral.step1': 'Share your referral URL with friends',
    'referral.step2': 'When they connect a wallet using your link, you get credited',
    'referral.step3': 'Earn valid referrals when they stream or watch for 60+ seconds',
    'referral.step4': 'Track your progress on the leaderboard',
    'referral.stats_title': 'Your Referral Stats',
    'referral.loading_stats': 'Loading stats...',
    'referral.total_referrals': 'Total Referrals',
    'referral.valid_referrals': 'Valid Referrals',
    'referral.status': 'Status',
    'referral.active': 'Active',
    'referral.recent_referrals': 'Recent Referrals',
    'referral.anonymous_user': 'Anonymous User',
    'referral.wallet_only': 'Referral system is available for wallet users only',
    'referral.wallet_only_description': 'Connect a wallet to access the referral system and earn rewards.',
    'referral.connect_required': 'Please connect your wallet to access the referral system',
    'referral.connect_description': 'Connect your wallet to generate your referral link and earn rewards.',

    // Staking
    'staking.title': 'Staking Coming Soon',
    'staking.description': 'We\'re working hard to bring you an amazing staking experience for WenLive.fun tokens.',
    'staking.what_to_expect': 'What to Expect',
    'staking.competitive_rewards': 'Competitive staking rewards',
    'staking.secure_pools': 'Secure and transparent staking pools',
    'staking.real_time_analytics': 'Real-time staking analytics',
    'staking.flexible_periods': 'Flexible staking periods',
    'staking.stay_tuned': 'Stay tuned for updates on our social channels!',

    // 404 Page
    'notfound.title': 'Page Not Found',
    'notfound.description': 'The page you are looking for doesn\'t exist or has been moved.',
    'notfound.return_home': 'Return to Home',

    // Streaming Pages
    'streaming.browser_title': 'Browser Streaming',
    'streaming.browser_description': 'Stream directly from your browser using your camera and microphone. No additional software required!',
    'streaming.obs_title': 'OBS/RTMP Streaming Setup',
    'streaming.obs_description': 'Configure OBS Studio or any RTMP-compatible software with your stream key to go live. Once a stream is ended, you\'ll need to create a new stream to broadcast again.',
    'streaming.wallet_required': 'Please connect your wallet to access streaming',
    'streaming.wallet_description': 'Wallet connection is required for streaming',
    'streaming.auth_required': 'Please authenticate your wallet',
    'streaming.auth_description': 'Wallet authentication is required for streaming',

    // Common Actions
    'action.copy': 'Copy',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.share': 'Share',
    'action.follow': 'Follow',
    'action.unfollow': 'Unfollow',
    'action.subscribe': 'Subscribe',
    'action.unsubscribe': 'Unsubscribe',
    'action.play': 'Play',
    'action.pause': 'Pause',
    'action.stop': 'Stop',
    'action.close': 'Close',
    'action.open': 'Open',
    'action.back': 'Back',
    'action.next': 'Next',
    'action.previous': 'Previous',
    'action.submit': 'Submit',
    'action.reset': 'Reset',

    // Creator/Become Creator Page
    'creator.program': 'Creator Program',
    'creator.become_title': 'Become a',
    'creator.solana': 'Solana',
    'creator.creator': 'Creator',
    'creator.hero_description': 'Share your Solana expertise, build an audience, and earn SOL directly from your supporters through livestreams, recorded content, and exclusive NFT access.',
    'creator.start_streaming': 'Start Streaming',
    'creator.connect_to_stream': 'Connect Wallet to Stream',
    'creator.watch_stories': 'Watch Creator Stories',
    'creator.why_create': 'Why Create on WenLive?',
    'creator.why_create_description': 'WenLive gives you the tools and audience to share your Solana knowledge while earning SOL directly from your supporters.',
    'creator.direct_earnings': 'Direct SOL Earnings',
    'creator.direct_earnings_description': 'Receive SOL donations directly to your wallet. While competitors charge up to 50% platform fees, we charge only 20%. Enjoy a no-KYC experience.',
    'creator.engaged_community': 'Engaged Community',
    'creator.engaged_community_description': 'Connect with Solana enthusiasts who share your interests and are looking for quality content and insights.',
    'creator.creator_rewards': 'Creator Rewards',
    'creator.creator_rewards_description': 'Top creators earn monthly rewards, exclusive NFTs, and opportunities to collaborate with Solana projects. (Coming Soon)',
    'creator.how_it_works': 'How It Works',
    'creator.how_it_works_description': 'Getting started as a WenLive creator is simple. Just follow these steps:',
    'creator.step1_title': 'Connect Wallet',
    'creator.step1_description': 'Connect your Solana wallet to establish your identity and receive donations.',
    'creator.step2_title': 'Create Your Profile',
    'creator.step2_description': 'Set up your creator profile with a username, display name, and avatar.',
    'creator.step3_title': 'Set Up Your Stream',
    'creator.step3_description': 'Configure your stream title, description, and other details.',
    'creator.step4_title': 'Start Streaming',
    'creator.step4_description': 'Go live with your first stream and start building your audience.',
    'creator.learn_to_stream': 'Learn How to Stream',
    'creator.learn_to_stream_description': 'Watch these quick tutorials to get started with streaming on WenLive.',
    'creator.video1_title': 'How to Stream on WenLive',
    'creator.video2_title': 'How to MultiStream on WenLive',
    'creator.content_types': 'Content You Can Create',
    'creator.content_types_description': 'Share your Solana expertise through various content formats:',
    'creator.educational_title': 'Educational Content',
    'creator.educational_description': 'Tutorials, guides, and educational content about Solana\'s ecosystem.',
    'creator.market_analysis_title': 'Market Analysis',
    'creator.market_analysis_description': 'Price predictions, token reviews, and technical analysis of the Solana market.',
    'creator.development_title': 'Development Tutorials',
    'creator.development_description': 'Coding tutorials for Solana smart contracts and dApp development.',
    'creator.nft_title': 'NFT Showcases',
    'creator.nft_description': 'NFT reveals, collection reviews, and artworks showcases.',
    'creator.ama_title': 'AMAs & Interviews',
    'creator.ama_description': 'Host AMAs with Solana developers, project founders and community members.',
    'creator.gaming_title': 'Gaming & P2E',
    'creator.gaming_description': 'Play-to-earn gaming streams, tournament broadcasts, and strategy guides.',
    'creator.vlogs_title': 'Vlogs & Lifestyle',
    'creator.vlogs_description': 'Share your daily life, thoughts, and experiences with your audience.',
    'creator.nsfw_title': 'MISC Content',
    'creator.nsfw_description': 'Miscellaneous content for diverse audiences. Ensure compliance with platform policies.',
    'creator.streaming_tips': 'Streaming Tips',
    'creator.streaming_tips_description': 'To ensure quality streams and engage with your audience effectively, here are some tips:',
    'creator.tip1': 'Use a stable internet connection with at least 5 Mbps upload speed',
    'creator.tip2': 'Ensure good lighting and clear audio for better viewer experience',
    'creator.tip3': 'Engage with your chat and respond to questions regularly',
    'creator.tip4': 'Promote your stream on your social media channels',
    'creator.tip5': 'Be consistent with your streaming schedule to build a regular audience',
    'creator.faq_title': 'Creator FAQ',
    'creator.faq1_question': 'How do I get paid for my streams?',
    'creator.faq1_answer': 'Viewers can send SOL donations directly to your connected wallet during streams. A 20% platform fee applies to these donations.',
    'creator.faq2_question': 'What equipment do I need?',
    'creator.faq2_answer': 'At minimum, you need a computer with a webcam and microphone. For better quality, we recommend a dedicated microphone and camera with good lighting.',
    'creator.faq3_question': 'Can I stream on other platforms simultaneously?',
    'creator.faq3_answer': 'Yes, WenLive allows simulcasting to other platforms.',
    'creator.faq4_question': 'How do I grow my audience?',
    'creator.faq4_answer': 'We feature new and trending creators on our homepage and provide promotional opportunities through our social channels for active creators.',
    'creator.faq5_question': 'Is there any review process for my streams?',
    'creator.faq5_answer': 'No. You can start streaming immediately after connecting your wallet, though we do have community guidelines that all creators must follow.',
    'creator.cta_title': 'Ready to Start Streaming?',
    'creator.cta_description': 'Connect your Solana wallet and start sharing your content with the world.',
    'creator.start_streaming_now': 'Start Streaming Now',
    'creator.start_quickly': 'Start in under a minute with just a few clicks',
    'creator.wallet_not_connected': 'Wallet not connected',
    'creator.connect_wallet_first': 'Please connect your Solana wallet first.',
    'creator.profile_check_error': 'Could not check profile',
    'creator.try_again': 'Please try again.',

    // Creator Setup Page
    'creator_setup.title': 'Become a Wenlive Creator',
    'creator_setup.description': 'Set up your creator profile to start streaming and engaging with your audience.',
    'creator_setup.profile_picture': 'Profile Picture',
    'creator_setup.profile_picture_description': 'Optional. Max 5MB. JPG, PNG, GIF, WEBP.',
    'creator_setup.display_name': 'Display Name',
    'creator_setup.display_name_placeholder': 'Your Creator Name',
    'creator_setup.display_name_required': 'Display Name *',
    'creator_setup.wallet_address': 'Wallet Address',
    'creator_setup.wallet_address_description': 'This is your unique Solana wallet address.',
    'creator_setup.full_name': 'Full Name (Optional)',
    'creator_setup.full_name_placeholder': 'Your Full Name',
    'creator_setup.email': 'Email (Optional)',
    'creator_setup.email_placeholder': 'your.email@example.com',
    'creator_setup.email_description': 'For communication and notifications. Not publicly visible.',
    'creator_setup.bio': 'Short Bio (Optional)',
    'creator_setup.bio_placeholder': 'Tell us about yourself and your content (max 200 characters)',
    'creator_setup.website_url': 'Website URL (Optional)',
    'creator_setup.website_placeholder': 'https://yourwebsite.com',
    'creator_setup.social_x': 'X (Twitter) URL (Optional)',
    'creator_setup.social_x_placeholder': 'https://x.com/yourprofile',
    'creator_setup.social_telegram': 'Telegram URL (Optional)',
    'creator_setup.social_telegram_placeholder': 'https://t.me/yourusername',
    'creator_setup.social_youtube': 'YouTube URL (Optional)',
    'creator_setup.social_youtube_placeholder': 'https://youtube.com/c/yourchannel',
    'creator_setup.social_instagram': 'Instagram URL (Optional)',
    'creator_setup.social_instagram_placeholder': 'https://instagram.com/yourprofile',
    'creator_setup.social_kick': 'Kick URL (Optional)',
    'creator_setup.social_kick_placeholder': 'https://kick.com/yourprofile',
    'creator_setup.social_twitch': 'Twitch URL (Optional)',
    'creator_setup.social_twitch_placeholder': 'https://twitch.tv/yourprofile',
    'creator_setup.content_categories': 'Content Categories (Optional)',
    'creator_setup.content_categories_description': 'Select all that apply.',
    'creator_setup.category_gaming': 'Gaming',
    'creator_setup.category_education': 'Education & Tutorials',
    'creator_setup.category_crypto': 'Crypto & DeFi',
    'creator_setup.category_nfts': 'NFTs & Collectibles',
    'creator_setup.category_development': 'Development & Coding',
    'creator_setup.category_art_music': 'Art & Music',
    'creator_setup.category_lifestyle': 'Lifestyle & Vlogging',
    'creator_setup.category_nsfw': 'MISC',
    'creator_setup.category_nsfw_note': '(Miscellaneous content)',
    'creator_setup.category_other': 'Other',
    'creator_setup.language_preference': 'Primary Language (Optional)',
    'creator_setup.language_placeholder': 'Select a language',
    'creator_setup.monetization_settings': 'Monetization Settings',
    'creator_setup.subscription_enabled': 'Enable Paid Subscriptions',
    'creator_setup.subscription_description': 'Gate your content behind a monthly SOL subscription.',
    'creator_setup.subscription_price': 'Monthly Subscription Price (SOL)',
    'creator_setup.subscription_price_placeholder': 'e.g., 0.5',
    'creator_setup.subscription_price_description': 'Set the price in SOL for a 30-day subscription.',
    'creator_setup.submit_button': 'Complete Profile & Start Creating',
    'creator_setup.submit_button_saving': 'Saving Profile...',
    'creator_setup.wallet_not_connected': 'Please connect your wallet to continue.',
    'creator_setup.wallet_missing_error': 'Wallet address is missing.',

    // Create Stream Page
    'create_stream.title': 'Create Your Stream',
    'create_stream.content_policy_title': 'Content Policy',
    'create_stream.content_policy_text': 'Our platform allows adult content and nudity but prohibits violent material, gore, and sexual activity. Streams are monitored by our AI system and will be automatically terminated if violations are detected.',
    'create_stream.streaming_method': 'Choose Streaming Method',
    'create_stream.obs_rtmp': 'OBS/RTMP',
    'create_stream.obs_rtmp_description': 'Use OBS Studio or any RTMP software',
    'create_stream.browser_streaming': 'Browser Streaming',
    'create_stream.browser_streaming_description': 'Stream directly from browser',
    'create_stream.stream_title': 'Stream Title',
    'create_stream.stream_title_placeholder': 'Enter a catchy title for your stream',
    'create_stream.description': 'Description',
    'create_stream.description_placeholder': 'What will you be sharing in this stream?',
    'create_stream.category': 'Category',
    'create_stream.category_placeholder': 'Select a category',
    'create_stream.language': 'Language',
    'create_stream.language_placeholder': 'Select a language',
    'create_stream.tags': 'Tags (comma separated)',
    'create_stream.tags_placeholder': 'solana, defi, crypto',
    'create_stream.create_setup_button': 'Create Stream Setup',
    'create_stream.create_browser_button': 'Create Stream & Go Live with Browser',
    'create_stream.creating_setup': 'Creating Stream Setup...',
    'create_stream.wallet_connect_first': 'Please connect your wallet to create a stream',
    'create_stream.connect_wallet': 'Connect Wallet',
    'create_stream.setup_created_title': 'Stream Setup Created!',
    'create_stream.setup_created_description': 'Your stream setup is ready. Configure OBS with the provided details to start streaming.',
    'create_stream.setup_ready_title': 'Stream Setup Ready!',
    'create_stream.setup_ready_description': 'Your stream details have been saved. You can now go live with browser streaming!',
    'create_stream.creation_failed': 'Stream Creation Failed',
    'create_stream.creation_error': 'There was an error creating your stream. Please try again.',
    'create_stream.profile_error': 'Profile Error',
    'create_stream.profile_not_found': 'Could not find your user profile. Please ensure your wallet is connected correctly.',
    'create_stream.title_min_error': 'Title must be at least 5 characters',
    'create_stream.title_max_error': 'Title must be at most 100 characters',
    'create_stream.description_min_error': 'Description must be at least 10 characters',
    'create_stream.description_max_error': 'Description must be at most 500 characters',
    'create_stream.category_required': 'Please select a category',
    'create_stream.language_required': 'Please select a language',
    'create_stream.invalid_contract_address': 'Invalid Solana contract address format',
    'create_stream.category_memecoins': 'Memecoins',
    'create_stream.category_gaming': 'Gaming',
    'create_stream.category_dev': 'Development',
    'create_stream.category_trading': 'Trading',
    'create_stream.category_education': 'Education',
    'create_stream.category_nsfw': 'MISC',
    'create_stream.language_english': 'English',
    'create_stream.language_spanish': 'Spanish',
    'create_stream.language_french': 'French',
    'create_stream.language_german': 'German',
    'create_stream.language_portuguese': 'Portuguese',
    'create_stream.language_russian': 'Russian',
    'create_stream.language_japanese': 'Japanese',
    'create_stream.language_korean': 'Korean',
    'create_stream.language_chinese_simplified': 'Chinese (Simplified)',
    'create_stream.language_chinese_traditional': 'Chinese (Traditional)',
    'create_stream.language_hindi': 'Hindi',
    'create_stream.language_arabic': 'Arabic',
    'create_stream.language_other': 'Other',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.browse': '浏览',
    'nav.following': '关注',
    'nav.explore': '探索创作者',
    'nav.become_creator': '成为创作者',
    'nav.how_it_works': '工作原理',
    'nav.leaderboard': '排行榜',
    'nav.staking': '质押',
    'nav.login': '登录',
    'nav.beta_stage': '测试版',
    
    // Categories
    'category.memecoins': '模因币',
    'category.gaming': '游戏',
    'category.development': '开发',
    'category.trading': '交易',
    'category.education': '教育',
    'category.nsfw': '杂项',
    'category.categories': '分类',
    'category.socials': '社交媒体',
    
    // User Menu
    'user.view_profile': '查看资料',
    'user.subscription_settings': '订阅设置',
    'user.obs_streaming': 'OBS 直播',
    'user.balance': '余额',
    'user.wallet': '钱包',
    'user.email': '邮箱',
    'user.sign_out': '退出登录',
    'user.disconnect': '断开连接',
    'user.connected_wallet': '已连接钱包',
    'user.google_user': '谷歌用户',
    
    // Socials
    'social.x_twitter': 'X (推特)',
    'social.telegram': '电报',
    'social.email': '邮箱',

    // Footer
    'footer.description': 'WenLive.fun 用户和创作者的终极流媒体平台。进行直播、捐赠，并与 WenLive.fun 社区互动。',
    'footer.platform': '平台',
    'footer.legal': '法律',
    'footer.connect': '联系',
    'footer.home': '首页',
    'footer.browse_streams': '浏览直播',
    'footer.creators': '创作者',
    'footer.terms_of_service': '服务条款',
    'footer.privacy_policy': '隐私政策',
    'footer.twitter': '推特',
    'footer.status': '状态',
    'footer.copyright': '保留所有权利。',

    // Following Page
    'following.login_description': '登录以关注创作者并查看他们的直播和录播。',
    'following.go_home': '返回首页',
    'following.description': '您关注的创作者的直播和录播',
    'following.no_content_title': '暂无内容',
    'following.no_content_description': '关注一些创作者，在这里查看他们的直播和录播。发现新的创作者来关注！',
    'following.live_tab': '直播',
    'following.vods_tab': '录播',
    'following.no_live_streams': '目前没有来自关注创作者的直播。',
    'following.no_vods': '暂无来自关注创作者的录播。',

    // Homepage
    'home.hero.title': '用 WenLive.fun 直播、连接和赚取',
    'home.hero.subtitle': 'Solana 上的去中心化流媒体平台',
    'home.hero.description': '创建直播、观看您喜爱的创作者，并在真正的去中心化环境中赚取奖励。',
    'home.hero.start_watching': '开始观看',
    'home.hero.become_creator': '成为创作者',
    'home.hero.tagline': '直播。赚取。重复。链上且不可阻挡——欢迎来到 WenLive.fun。',
    'home.contract_address': '合约地址',
    'home.copy_address': '复制地址',
    'home.address_copied': '地址已复制到剪贴板！',
    'home.contract_copied': '合约地址已复制到剪贴板！',
    'home.live_channels': '直播频道',
    'home.featured_creators': '🔥 精选创作者',
    'home.creator_uploads': '创作者上传',
    'home.recently_streamed': '最近直播',
    'home.no_live_streams': '目前没有直播',
    'home.no_uploads': '暂无创作者上传内容',
    'home.no_recent_vods': '暂无最近录播',
    'home.no_live_or_creators': '目前没有直播或精选创作者',
    'home.no_uploaded_videos': '暂无上传视频',
    'home.no_past_streams': '暂无过往直播',
    'home.view_all_streams': '查看所有直播',
    'home.view_all_uploads': '查看所有上传',
    'home.view_all_vods': '查看所有录播',
    'home.view_all_live': '查看所有直播 →',
    'home.view_all_uploads_link': '查看所有上传 →',
    'home.view_all_vods_link': '查看所有录播 →',
    'home.loading_streams': '正在加载直播...',
    'home.loading_uploads': '正在加载创作者上传...',
    'home.loading_vods': '正在加载最近录播...',
    'home.loading_content': '正在加载内容...',
    'home.refresh': '刷新',
    'home.be_first_live': '成为第一个直播的人！',
    'home.start_uploading': '开始上传内容！',
    'home.start_creating': '开始创建内容！',
    'home.failed_live_streams': '加载直播失败。请尝试刷新。',
    'home.failed_uploads': '加载上传视频失败。请尝试刷新。',
    'home.failed_recent_videos': '加载最近视频失败。请尝试刷新。',

    // StartWatching Page
    'watch.discover_category': '按分类发现内容',
    'watch.explore_category': '探索',
    'watch.content': '内容',
    'watch.find_content': '在',
    'watch.category_text': '分类中寻找直播和录播。',
    'watch.browse_categories': '浏览各种分类，找到您感兴趣的直播、录播和其他内容。',
    'watch.search_placeholder': '搜索直播或创作者（即将推出）',
    'watch.search': '搜索',
    'watch.live_streams': '直播',
    'watch.vods': '录播',
    'watch.total': '总计',
    'watch.no_content_category': '在',
    'watch.at_moment': '中暂时没有找到内容。',
    'watch.view_all_categories': '查看所有分类',
    'watch.no_content_available': '在',
    'watch.load_more': '加载更多',
    'watch.remaining': '剩余',
    'watch.no_categories': '暂无可显示的分类。',

    // Content States
    'content.loading': '加载中...',
    'content.error': '加载内容出错',
    'content.no_content': '暂无内容',
    'content.try_again': '重试',
    'content.load_more': '加载更多',
    'content.refresh': '刷新',
    'content.search_placeholder': '搜索创作者、直播、录播...',

    // Stream States
    'stream.live': '直播中',
    'stream.upload': '上传',
    'stream.processing': '处理中',
    'stream.vod': '录播',
    'stream.offline': '离线',
    'stream.starting': '启动中',
    'stream.viewers': '观众',
    'stream.viewer': '观众',
    'stream.watching': '观看中',
    'stream.processing_text': '处理中...',

    // Time
    'time.just_now': '刚刚',
    'time.minute_ago': '分钟前',
    'time.minutes_ago': '分钟前',
    'time.hour_ago': '小时前',
    'time.hours_ago': '小时前',
    'time.day_ago': '天前',
    'time.days_ago': '天前',
    'time.week_ago': '周前',
    'time.weeks_ago': '周前',
    'time.month_ago': '月前',
    'time.months_ago': '月前',
    'time.year_ago': '年前',
    'time.years_ago': '年前',

    // Browse Page
    'browse.title': '浏览内容',
    'browse.subtitle': '发现创作者的直播和视频',
    'browse.live_streams': '直播',
    'browse.recent_vods': '最近录播',
    'browse.no_streams': '暂无直播',
    'browse.no_vods': '暂无录播',
    'browse.filter_by_category': '按分类筛选',
    'browse.all_categories': '所有分类',

    // VODs Page
    'vods.title': '所有录播',
    'vods.subtitle': '探索我们创作者的所有录制直播和内容',
    'vods.total_count': '总计',
    'vods.no_vods': '暂无录播',
    'vods.no_vods_description': '目前没有可用的录制直播。',
    'vods.loading': '正在加载录播...',
    'vods.error': '加载录播出错',
    'vods.error_description': '无法加载视频内容。请稍后重试。',
    'vods.remaining': '剩余',

    // Explore Creators
    'explore.title': '探索创作者',
    'explore.subtitle': '发现我们平台上的优秀创作者。',
    'explore.no_creators': '暂未找到创作者。',
    'explore.no_creators_description': '请稍后再来查看或成为第一个创建资料的人！',
    'explore.error_loading': '加载创作者出错',
    'explore.error_description': '获取创作者资料时出现错误。',

    // Leaderboard
    'leaderboard.title': '排行榜',
    'leaderboard.subtitle': '顶级表现者和推荐者',
    'leaderboard.creators': '创作者',
    'leaderboard.referrals': '推荐',
    'leaderboard.creator_title': '创作者排行榜',
    'leaderboard.creator_subtitle': '自 2025 年 6 月 28 日以来的顶级创作者',
    'leaderboard.no_data': '暂无创作者数据。',
    'leaderboard.streams': '直播',
    'leaderboard.total_hours': '总时长',
    'leaderboard.champion': '冠军',
    'leaderboard.runner_up': '亚军',
    'leaderboard.third_place': '季军',
    'leaderboard.referral_title': '推荐排行榜',
    'leaderboard.rank': '排名',
    'leaderboard.user': '用户',
    'leaderboard.total': '总计',
    'leaderboard.valid': '有效',
    'leaderboard.last_activity': '最后活动',
    'leaderboard.no_referrals': '暂无推荐！',
    'leaderboard.no_referrals_description': '成为第一个推荐朋友并占领榜首位置。',
    'leaderboard.referral_system': '推荐系统',
    'leaderboard.total_referrals_desc': '使用您的链接注册的用户',
    'leaderboard.valid_referrals_desc': '观看或直播超过 60 秒的用户',
    'leaderboard.ranking_desc': '按有效推荐排序，然后按总推荐排序',
    'leaderboard.loading': '正在加载排行榜...',

    // Referral System
    'referral.title': '您的推荐链接',
    'referral.url_label': '推荐链接',
    'referral.copy_url': '复制链接',
    'referral.url_copied': '推荐链接已复制到剪贴板！',
    'referral.how_it_works': '工作原理：',
    'referral.step1': '与朋友分享您的推荐链接',
    'referral.step2': '当他们使用您的链接连接钱包时，您将获得积分',
    'referral.step3': '当他们观看或直播超过 60 秒时，您将获得有效推荐',
    'referral.step4': '在排行榜上跟踪您的进度',
    'referral.stats_title': '您的推荐统计',
    'referral.loading_stats': '正在加载统计...',
    'referral.total_referrals': '总推荐数',
    'referral.valid_referrals': '有效推荐数',
    'referral.status': '状态',
    'referral.active': '活跃',
    'referral.recent_referrals': '最近推荐',
    'referral.anonymous_user': '匿名用户',
    'referral.wallet_only': '推荐系统仅适用于钱包用户',
    'referral.wallet_only_description': '连接钱包以访问推荐系统并赚取奖励。',
    'referral.connect_required': '请连接您的钱包以访问推荐系统',
    'referral.connect_description': '连接您的钱包以生成推荐链接并赚取奖励。',

    // Staking
    'staking.title': '质押即将推出',
    'staking.description': '我们正在努力为您带来 WenLive.fun 代币的惊人质押体验。',
    'staking.what_to_expect': '期待什么',
    'staking.competitive_rewards': '有竞争力的质押奖励',
    'staking.secure_pools': '安全透明的质押池',
    'staking.real_time_analytics': '实时质押分析',
    'staking.flexible_periods': '灵活的质押期限',
    'staking.stay_tuned': '敬请关注我们社交媒体上的更新！',

    // 404 Page
    'notfound.title': '页面未找到',
    'notfound.description': '您要查找的页面不存在或已移动。',
    'notfound.return_home': '返回首页',

    // Streaming Pages
    'streaming.browser_title': '浏览器直播',
    'streaming.browser_description': '直接从浏览器使用摄像头和麦克风进行直播。无需额外软件！',
    'streaming.obs_title': 'OBS/RTMP 直播设置',
    'streaming.obs_description': '使用您的直播密钥配置 OBS Studio 或任何兼容 RTMP 的软件进行直播。直播结束后，您需要创建新的直播才能再次广播。',
    'streaming.wallet_required': '请连接您的钱包以访问直播',
    'streaming.wallet_description': '直播需要钱包连接',
    'streaming.auth_required': '请验证您的钱包',
    'streaming.auth_description': '直播需要钱包验证',

    // Common Actions
    'action.copy': '复制',
    'action.save': '保存',
    'action.cancel': '取消',
    'action.delete': '删除',
    'action.edit': '编辑',
    'action.share': '分享',
    'action.follow': '关注',
    'action.unfollow': '取消关注',
    'action.subscribe': '订阅',
    'action.unsubscribe': '取消订阅',
    'action.play': '播放',
    'action.pause': '暂停',
    'action.stop': '停止',
    'action.close': '关闭',
    'action.open': '打开',
    'action.back': '返回',
    'action.next': '下一个',
    'action.previous': '上一个',
    'action.submit': '提交',
    'action.reset': '重置',

    // Creator/Become Creator Page
    'creator.program': '创作者计划',
    'creator.become_title': '成为',
    'creator.solana': 'Solana',
    'creator.creator': '创作者',
    'creator.hero_description': '分享您的 Solana 专业知识，建立受众群体，并通过直播、录制内容和独家 NFT 访问权限直接从支持者那里赚取 SOL。',
    'creator.start_streaming': '开始直播',
    'creator.connect_to_stream': '连接钱包开始直播',
    'creator.watch_stories': '观看创作者故事',
    'creator.why_create': '为什么在 WenLive 上创作？',
    'creator.why_create_description': 'WenLive 为您提供工具和受众群体，让您分享 Solana 知识，同时直接从支持者那里赚取 SOL。',
    'creator.direct_earnings': '直接 SOL 收益',
    'creator.direct_earnings_description': '直接接收 SOL 捐赠到您的钱包。虽然竞争对手收取高达 50% 的平台费用，但我们只收取 20%。享受无需 KYC 的体验。',
    'creator.engaged_community': '活跃社区',
    'creator.engaged_community_description': '与 Solana 爱好者联系，他们与您有共同兴趣，正在寻找优质内容和见解。',
    'creator.creator_rewards': '创作者奖励',
    'creator.creator_rewards_description': '顶级创作者赚取月度奖励、独家 NFT 以及与 Solana 项目合作的机会。（即将推出）',
    'creator.how_it_works': '工作原理',
    'creator.how_it_works_description': '成为 WenLive 创作者很简单。只需遵循以下步骤：',
    'creator.step1_title': '连接钱包',
    'creator.step1_description': '连接您的 Solana 钱包以确立身份并接收捐赠。',
    'creator.step2_title': '创建您的资料',
    'creator.step2_description': '设置您的创作者资料，包括用户名、显示名称和头像。',
    'creator.step3_title': '设置您的直播',
    'creator.step3_description': '配置您的直播标题、描述和其他详细信息。',
    'creator.step4_title': '开始直播',
    'creator.step4_description': '开始您的第一次直播并建立您的受众群体。',
    'creator.learn_to_stream': '学习如何直播',
    'creator.learn_to_stream_description': '观看这些快速教程，开始在 WenLive 上直播。',
    'creator.video1_title': '如何在 WenLive 上直播',
    'creator.video2_title': '如何在 WenLive 上多平台直播',
    'creator.content_types': '您可以创建的内容',
    'creator.content_types_description': '通过各种内容格式分享您的 Solana 专业知识：',
    'creator.educational_title': '教育内容',
    'creator.educational_description': '关于 Solana 生态系统的教程、指南和教育内容。',
    'creator.market_analysis_title': '市场分析',
    'creator.market_analysis_description': 'Solana 市场的价格预测、代币评论和技术分析。',
    'creator.development_title': '开发教程',
    'creator.development_description': 'Solana 智能合约和 dApp 开发的编程教程。',
    'creator.nft_title': 'NFT 展示',
    'creator.nft_description': 'NFT 揭示、收藏评论和艺术作品展示。',
    'creator.ama_title': 'AMA 和访谈',
    'creator.ama_description': '与 Solana 开发者、项目创始人和社区成员主持 AMA。',
    'creator.gaming_title': '游戏和 P2E',
    'creator.gaming_description': '边玩边赚游戏直播、锦标赛广播和策略指南。',
    'creator.vlogs_title': 'Vlog 和生活方式',
    'creator.vlogs_description': '与您的观众分享您的日常生活、想法和体验。',
    'creator.nsfw_title': '杂项内容',
    'creator.nsfw_description': '面向多样化观众的杂项内容。确保符合平台政策。',
    'creator.streaming_tips': '直播技巧',
    'creator.streaming_tips_description': '为了确保高质量的直播并有效地与您的观众互动，以下是一些建议：',
    'creator.tip1': '使用至少 5 Mbps 上传速度的稳定网络连接',
    'creator.tip2': '确保良好的照明和清晰的音频以获得更好的观看体验',
    'creator.tip3': '与您的聊天室互动并定期回答问题',
    'creator.tip4': '在您的社交媒体渠道上推广您的直播',
    'creator.tip5': '保持一致的直播时间表以建立固定观众群体',
    'creator.faq_title': '创作者常见问题',
    'creator.faq1_question': '我如何从直播中获得报酬？',
    'creator.faq1_answer': '观众可以在直播期间直接向您连接的钱包发送 SOL 捐赠。这些捐赠适用 20% 的平台费用。',
    'creator.faq2_question': '我需要什么设备？',
    'creator.faq2_answer': '至少需要一台带有网络摄像头和麦克风的计算机。为了获得更好的质量，我们建议使用专用麦克风和摄像头以及良好的照明。',
    'creator.faq3_question': '我可以同时在其他平台上直播吗？',
    'creator.faq3_answer': '是的，WenLive 允许同时向其他平台直播。',
    'creator.faq4_question': '我如何增长我的观众群体？',
    'creator.faq4_answer': '我们在主页上展示新的和热门的创作者，并为活跃的创作者提供通过我们社交渠道的推广机会。',
    'creator.faq5_question': '我的直播有审核流程吗？',
    'creator.faq5_answer': '没有。连接钱包后您可以立即开始直播，不过我们确实有所有创作者必须遵循的社区准则。',
    'creator.cta_title': '准备开始直播了吗？',
    'creator.cta_description': '连接您的 Solana 钱包并开始与世界分享您的内容。',
    'creator.start_streaming_now': '立即开始直播',
    'creator.start_quickly': '只需几次点击即可在一分钟内开始',
    'creator.wallet_not_connected': '钱包未连接',
    'creator.connect_wallet_first': '请先连接您的 Solana 钱包。',
    'creator.profile_check_error': '无法检查资料',
    'creator.try_again': '请重试。',

    // Creator Setup Page
    'creator_setup.title': '成为 Wenlive 创作者',
    'creator_setup.description': '设置您的创作者资料以开始直播并与观众互动。',
    'creator_setup.profile_picture': '头像',
    'creator_setup.profile_picture_description': '可选。最大 5MB。支持 JPG、PNG、GIF、WEBP 格式。',
    'creator_setup.display_name': '显示名称',
    'creator_setup.display_name_placeholder': '您的创作者名称',
    'creator_setup.display_name_required': '显示名称 *',
    'creator_setup.wallet_address': '钱包地址',
    'creator_setup.wallet_address_description': '这是您独特的 Solana 钱包地址。',
    'creator_setup.full_name': '全名（可选）',
    'creator_setup.full_name_placeholder': '您的全名',
    'creator_setup.email': '邮箱（可选）',
    'creator_setup.email_placeholder': 'your.email@example.com',
    'creator_setup.email_description': '用于通信和通知。不会公开显示。',
    'creator_setup.bio': '简短介绍（可选）',
    'creator_setup.bio_placeholder': '介绍一下您自己和您的内容（最多 200 字符）',
    'creator_setup.website_url': '网站链接（可选）',
    'creator_setup.website_placeholder': 'https://yourwebsite.com',
    'creator_setup.social_x': 'X (推特) 链接（可选）',
    'creator_setup.social_x_placeholder': 'https://x.com/yourprofile',
    'creator_setup.social_telegram': '电报链接（可选）',
    'creator_setup.social_telegram_placeholder': 'https://t.me/yourusername',
    'creator_setup.social_youtube': 'YouTube 链接（可选）',
    'creator_setup.social_youtube_placeholder': 'https://youtube.com/c/yourchannel',
    'creator_setup.social_instagram': 'Instagram 链接（可选）',
    'creator_setup.social_instagram_placeholder': 'https://instagram.com/yourprofile',
    'creator_setup.social_kick': 'Kick 链接（可选）',
    'creator_setup.social_kick_placeholder': 'https://kick.com/yourprofile',
    'creator_setup.social_twitch': 'Twitch 链接（可选）',
    'creator_setup.social_twitch_placeholder': 'https://twitch.tv/yourprofile',
    'creator_setup.content_categories': '内容分类（可选）',
    'creator_setup.content_categories_description': '选择所有适用的分类。',
    'creator_setup.category_gaming': '游戏',
    'creator_setup.category_education': '教育与教程',
    'creator_setup.category_crypto': '加密货币与 DeFi',
    'creator_setup.category_nfts': 'NFT 与收藏品',
    'creator_setup.category_development': '开发与编程',
    'creator_setup.category_art_music': '艺术与音乐',
    'creator_setup.category_lifestyle': '生活方式与 Vlog',
    'creator_setup.category_nsfw': '杂项',
    'creator_setup.category_nsfw_note': '（杂项内容）',
    'creator_setup.category_other': '其他',
    'creator_setup.language_preference': '主要语言（可选）',
    'creator_setup.language_placeholder': '选择语言',
    'creator_setup.monetization_settings': '变现设置',
    'creator_setup.subscription_enabled': '启用付费订阅',
    'creator_setup.subscription_description': '将您的内容设置为需要月度 SOL 订阅才能访问。',
    'creator_setup.subscription_price': '月度订阅价格（SOL）',
    'creator_setup.subscription_price_placeholder': '例如：0.5',
    'creator_setup.subscription_price_description': '设置 30 天订阅的 SOL 价格。',
    'creator_setup.submit_button': '完成资料并开始创作',
    'creator_setup.submit_button_saving': '正在保存资料...',
    'creator_setup.wallet_not_connected': '请连接您的钱包以继续。',
    'creator_setup.wallet_missing_error': '缺少钱包地址。',

    // Create Stream Page
    'create_stream.title': '创建您的直播',
    'create_stream.content_policy_title': '内容政策',
    'create_stream.content_policy_text': '我们的平台允许成人内容和裸体，但禁止暴力材料、血腥内容和性行为。直播内容受我们的AI系统监控，如果检测到违规内容将自动终止。',
    'create_stream.streaming_method': '选择直播方式',
    'create_stream.obs_rtmp': 'OBS/RTMP',
    'create_stream.obs_rtmp_description': '使用 OBS Studio 或任何 RTMP 软件',
    'create_stream.browser_streaming': '浏览器直播',
    'create_stream.browser_streaming_description': '直接从浏览器开始直播',
    'create_stream.stream_title': '直播标题',
    'create_stream.stream_title_placeholder': '为您的直播输入一个吸引人的标题',
    'create_stream.description': '描述',
    'create_stream.description_placeholder': '您将在这个直播中分享什么内容？',
    'create_stream.category': '分类',
    'create_stream.category_placeholder': '选择一个分类',
    'create_stream.language': '语言',
    'create_stream.language_placeholder': '选择一种语言',
    'create_stream.tags': '标签（逗号分隔）',
    'create_stream.tags_placeholder': 'solana, defi, 加密货币',
    'create_stream.launching_token': '发布代币？',
    'create_stream.launching_token_description': '如果您在此次直播中发布或推广特定代币，请启用此选项。',
    'create_stream.token_platforms': '代币发布平台：',
    'create_stream.token_contract_address': '输入代币合约地址（CA）',
    'create_stream.token_contract_placeholder': '例如：7sM9...Do5n8（Solana 地址）',
    'create_stream.create_setup_button': '创建直播设置',
    'create_stream.create_browser_button': '创建直播并使用浏览器开始直播',
    'create_stream.creating_setup': '正在创建直播设置...',
    'create_stream.wallet_connect_first': '请连接您的钱包以创建直播',
    'create_stream.connect_wallet': '连接钱包',
    'create_stream.setup_created_title': '直播设置已创建！',
    'create_stream.setup_created_description': '您的直播设置已准备就绪。使用提供的详细信息配置 OBS 以开始直播。',
    'create_stream.setup_ready_title': '直播设置就绪！',
    'create_stream.setup_ready_description': '您的直播详细信息已保存。您现在可以使用浏览器直播开始直播！',
    'create_stream.creation_failed': '直播创建失败',
    'create_stream.creation_error': '创建直播时出现错误。请重试。',
    'create_stream.profile_error': '资料错误',
    'create_stream.profile_not_found': '找不到您的用户资料。请确保您的钱包已正确连接。',
    'create_stream.title_min_error': '标题至少需要5个字符',
    'create_stream.title_max_error': '标题最多100个字符',
    'create_stream.description_min_error': '描述至少需要10个字符',
    'create_stream.description_max_error': '描述最多500个字符',
    'create_stream.category_required': '请选择一个分类',
    'create_stream.language_required': '请选择一种语言',
    'create_stream.invalid_contract_address': 'Solana合约地址格式无效',
    'create_stream.category_memecoins': '模因币',
    'create_stream.category_gaming': '游戏',
    'create_stream.category_dev': '开发',
    'create_stream.category_trading': '交易',
    'create_stream.category_education': '教育',
    'create_stream.category_nsfw': '杂项',
    'create_stream.language_english': '英语',
    'create_stream.language_spanish': '西班牙语',
    'create_stream.language_french': '法语',
    'create_stream.language_german': '德语',
    'create_stream.language_portuguese': '葡萄牙语',
    'create_stream.language_russian': '俄语',
    'create_stream.language_japanese': '日语',
    'create_stream.language_korean': '韩语',
    'create_stream.language_chinese_simplified': '中文（简体）',
    'create_stream.language_chinese_traditional': '中文（繁体）',
    'create_stream.language_hindi': '印地语',
    'create_stream.language_arabic': '阿拉伯语',
    'create_stream.language_other': '其他',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('wenlive-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('wenlive-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
